// Code generated by Kitex v0.9.1. DO NOT EDIT.
package salaryservice

import (
	server "github.com/cloudwego/kitex/server"
	salary "github.com/garfield-dev-team/kitex_gorm/kitex_gen/salary"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler salary.SalaryService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler salary.SalaryService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
